spring:
  application:
    name: payment-service


  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://payment-service-postgres:5432/parser_service_db
    username: admin
    password: password

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: false
    properties:
      hibernate.hibernate.format_sql: true
      hibernate.use_sql_comments: true
      hibernate.jdbc.batch_size: 30


thread-pool-task-executor:
  core-pool-size: 12
  max-pool-size: 12
  queue-capacity: 50
  thread-name-prefix: Scraper-

webdriver:
  args:
    - --headless=new
    - --disable-gpu
    - --no-sandbox
    - --disable-dev-shm-usage
    - --window-size=1920,1080
    - user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)...

scraper:
  goodreads:
    base-url: "https://www.goodreads.com/list/show/1.Best_Books_Ever?page="
    book-selector: "tr[itemtype='http://schema.org/Book']"
    selectors:
      book: "tr[itemtype='http://schema.org/Book']"
      title: ".bookTitle"
      author: ".authorName"
      rating: ".minirating"